### ISSUE TITLE
Problem with project structure

### ISSUE THREAD

**Issue by nektonick** [Motiarti/Tests#3]
Структура проекта не совпадает с общепринятой для Java.
Про общепринятую структуру можно почитать, например, здесь: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by Moriarti85** [comment]
Вроде поправил

**Comment by nektonick** [comment]
> Вроде поправил

Осталось залить в основную ветку

**Comment by Moriarti85** [comment]
влил в мастер
